# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exercise_Page_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Exercise(object):
    def setupUi(self, Exercise):
        Exercise.setObjectName("Exercise")
        Exercise.resize(1920, 1080)
        Exercise.setMaximumSize(QtCore.QSize(1920, 1080))
        Exercise.setStyleSheet("background-color : rgb(255, 255, 255)")
        self.label = QtWidgets.QLabel(Exercise)
        self.label.setGeometry(QtCore.QRect(200, 290, 350, 350))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Exercise)
        self.label_2.setGeometry(QtCore.QRect(800, 290, 350, 350))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Exercise)
        self.label_3.setGeometry(QtCore.QRect(1380, 290, 350, 350))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Exercise)
        self.label_4.setGeometry(QtCore.QRect(200, 690, 1531, 60))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Exercise)
        self.label_5.setGeometry(QtCore.QRect(200, 740, 1531, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color : rgb(217, 217, 217)")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Exercise)
        QtCore.QMetaObject.connectSlotsByName(Exercise)

    def retranslateUi(self, Exercise):
        _translate = QtCore.QCoreApplication.translate
        Exercise.setWindowTitle(_translate("Exercise", "Exercise"))
        self.label.setText(_translate("Exercise", "TextLabel"))
        self.label_2.setText(_translate("Exercise", "TextLabel"))
        self.label_3.setText(_translate("Exercise", "TextLabel"))
        self.label_4.setText(_translate("Exercise", "진행할 운동을 선택하세요"))
        self.label_5.setText(_translate("Exercise", "(Enter를 누르면 선택돼요)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Exercise = QtWidgets.QDialog()
    ui = Ui_Exercise()
    ui.setupUi(Exercise)
    Exercise.show()
    sys.exit(app.exec_())
